# SPDX-License-Identifier: GPL-3.0-or-later
# Read the Docs configuration file
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - git submodule update --init --recursive

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf

submodules:
  include: all
  recursive: true
